In [62]:
import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error ,r2_score,accuracy_score, classification_report
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [11]:
lr= LinearRegression()

In [20]:
scl = StandardScaler()

In [13]:
df=pd.read_excel("Concrete_Data.xls",decimal=",")

In [14]:
df.columns

Index(['Cement (component 1)(kg in a m^3 mixture)',
       'Blast Furnace Slag (component 2)(kg in a m^3 mixture)',
       'Fly Ash (component 3)(kg in a m^3 mixture)',
       'Water  (component 4)(kg in a m^3 mixture)',
       'Superplasticizer (component 5)(kg in a m^3 mixture)',
       'Coarse Aggregate  (component 6)(kg in a m^3 mixture)',
       'Fine Aggregate (component 7)(kg in a m^3 mixture)', 'Age (day)',
       'Concrete compressive strength(MPa, megapascals) '],
      dtype='object')

In [15]:
df.columns=['Cement', 'Slag', 'FlyAsh', 'Water', 'Plasticizer', 'CoarseAgg', 'FineAgg', 'Age', 'Strength']

In [16]:
df.head()

,Cement,Slag,FlyAsh,Water,Plasticizer,CoarseAgg,FineAgg,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.986111
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.887366
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.269535
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.052780
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.296075

In [17]:
df.describe()

,Cement,Slag,FlyAsh,Water,Plasticizer,CoarseAgg,FineAgg,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.165631,73.895485,54.187136,181.566359,6.203112,972.918592,773.578883,45.662136,35.817836
std,104.507142,86.279104,63.996469,21.355567,5.973492,77.753818,80.175427,63.169912,16.705679
min,102.000000,0.000000,0.000000,121.750000,0.000000,801.000000,594.000000,1.000000,2.331808
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.707115
50%,272.900000,22.000000,0.000000,185.000000,6.350000,968.000000,779.510000,28.000000,34.442774
75%,350.000000,142.950000,118.270000,192.000000,10.160000,1029.400000,824.000000,56.000000,46.136287
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.599225

In [18]:
df.isnull().sum()

Cement         0
Slag           0
FlyAsh         0
Water          0
Plasticizer    0
CoarseAgg      0
FineAgg        0
Age            0
Strength       0
dtype: int64

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import  StandardScaler

In [21]:
x=df.drop("Strength",axis=1)
y=df["Strength"]

In [22]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [23]:
x_train_scaled=scl.fit_transform(x_train)

In [24]:
x_test_scaled=scl.transform(x_test)

In [25]:
lr.fit(x_train_scaled, y_train)
lr_tahmin = lr.predict(x_test_scaled)

In [26]:
lr_r2=r2_score(y_test,lr_tahmin)
lr_rmse=np.sqrt(mean_squared_error(y_test,lr_tahmin))

In [27]:
lr_r2

0.6275416055429022

In [28]:
lr_rmse

np.float64(9.796707832398443)

In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
pd.set_option("display.max_columns",100)

from sklearn.linear_model import LinearRegression,SGDRegressor,Ridge,Lasso,ElasticNet
from sklearn.neighbors import KNeighborsRegressor, RadiusNeighborsRegressor
from sklearn.ensemble import GradientBoostingRegressor,AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor, plot_tree, ExtraTreeRegressor
#pip install xgboost
from xgboost import XGBRegressor
from sklearn.svm import SVR

from sklearn.neural_network import MLPRegressor

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

def algo_test(x,y):
        #Bütün modelleri tanımlıyorum
        L=LinearRegression()
        R=Ridge()
        Lass=Lasso()
        E=ElasticNet()
        sgd=SGDRegressor()
        ETR=ExtraTreeRegressor()
        GBR=GradientBoostingRegressor()
        kn=KNeighborsRegressor()
        rkn=RadiusNeighborsRegressor(radius=1.0)
        ada=AdaBoostRegressor()
        dt=DecisionTreeRegressor()
        xgb=XGBRegressor()
        svr=SVR()
        mlp_regressor = MLPRegressor()

       
        
        algos=[L,R,Lass,E,sgd,ETR,GBR,ada,kn,dt,xgb,svr,mlp_regressor]
        algo_names=['Linear','Ridge','Lasso','ElasticNet','SGD','Extra Tree','Gradient Boosting',
                    'KNeighborsRegressor','AdaBoost','Decision Tree','XGBRegressor','SVR','mlp_regressor']
        x=MinMaxScaler().fit_transform(x)
        x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=.20,random_state=42)
        
        r_squared= []
        rmse= []
        mae= []
        
        #Hata ve doğruluk oranlarını bir tablo haline getirmek için bir dataframe oluşturuyorum
        result=pd.DataFrame(columns=['R_Squared','RMSE','MAE'],index=algo_names)
        
        
        for algo in algos:
            p=algo.fit(x_train,y_train).predict(x_test)
            r_squared.append(r2_score(y_test,p))
            rmse.append(mean_squared_error(y_test,p)**.5)
            mae.append(mean_absolute_error(y_test,p))
        
            

        #result adlı tabloya doğruluk ve hata oranlarımı yerleştiriyorum
        result.R_Squared=r_squared
        result.RMSE=rmse
        result.MAE=mae
        
       #oluşturduğum result tablosunu doğruluk oranına (r2_score) göre sıralayıp dönüyor
        rtable=result.sort_values('R_Squared',ascending=False)
        return rtable

In [30]:
algo_test(x,y)

                     R_Squared       RMSE        MAE
XGBRegressor          0.923075   4.452198   2.906828
Gradient Boosting     0.880831   5.541446   4.099259
Decision Tree         0.809880   6.999310   4.537135
Extra Tree            0.777867   7.565681   4.946467
KNeighborsRegressor   0.753905   7.963294   6.600711
AdaBoost              0.684380   9.018273   6.981992
Linear                0.627542   9.796708   7.745393
Ridge                 0.625482   9.823755   7.864789
SGD                   0.619786   9.898176   7.951599
SVR                   0.606672  10.067426   8.097911
mlp_regressor         0.486129  11.507160   9.467525
Lasso                 0.188441  14.461104  11.926352
ElasticNet            0.055276  15.602480  12.708092

In [31]:
xgb=XGBRegressor()

In [32]:
xgb.fit(x_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [33]:
tahminXGB=xgb.predict(x_test)

In [34]:
r2_score(y_test,tahminXGB)

0.9230751936264272

In [35]:
# Geleneksel makine öğrenmesi modelleri ile sonucumuzu yuzde 92 dogruluk oranıyrla bulduk şimdi bunu Deep Learning ile deniyeceğiz

In [36]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Conv2D,Input,Reshape,MaxPooling2D,Flatten ,Dropout ,BatchNormalization

In [37]:
model=Sequential()
model.add(Dense(80,activation="relu")) # hayal urunu
model.add(Dense(120,activation="relu"))
model.add(Dense(64,activation="relu"))
model.add(Dense(30,activation="relu"))
model.add(Dense(8,activation="relu"))
model.add(Dense(1)) # regression olduğundan sigmoid yok 
model.compile(loss="mean_squared_error",optimizer="adam")

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [38]:
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=.20,random_state=42)

In [39]:
history=model.fit(x_train,y_train,batch_size=64, validation_data=(x_test,y_test),verbose=1,epochs=120)

Epoch 1/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 5s 46ms/step - loss: 2095.1758 - val_loss: 1085.8568
Epoch 2/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 538.1861 - val_loss: 394.2422
Epoch 3/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 306.1383 - val_loss: 266.2888
Epoch 4/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 261.0420 - val_loss: 230.2842
Epoch 5/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 235.3642 - val_loss: 214.3766
Epoch 6/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 218.8300 - val_loss: 207.7480
Epoch 7/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 209.3430 - val_loss: 195.6451
Epoch 8/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 198.7566 - val_loss: 187.7352
Epoch 9/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 187.2216 - val_loss: 177.7573
Epoch 10/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 178.4246 - val_loss: 163.4622
Epoch 11/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 164.7642 - val_loss: 149.5517
Epoch 12/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 150.7379 - val_loss: 138.1226
Epoch 13/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 140.6320 - val_loss: 131.8040
Epoch 14/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 129.3521 - val_loss: 113.6327
Epoch 15/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 120.2702 - val_loss: 109.1929
Epoch 16/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 113.9625 - val_loss: 101.0548
Epoch 17/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 107.7079 - val_loss: 93.2020
Epoch 18/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 101.4326 - val_loss: 89.9869
Epoch 19/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 96.9643 - val_loss: 80.0692
Epoch 20/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 87.8067 - val_loss: 75.8659
Epoch 21/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 84.3956 - val_loss: 71.8141
Epoch 22/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 82.3540 - val_loss: 69.3371
Epoch 23/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 75.5077 - val_loss: 62.8694
Epoch 24/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 84.8200 - val_loss: 74.5749
Epoch 25/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 70.6056 - val_loss: 60.0986
Epoch 26/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 66.3545 - val_loss: 57.5683
Epoch 27/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 64.5574 - val_loss: 55.7834
Epoch 28/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 65.3607 - val_loss: 56.0312
Epoch 29/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 62.7871 - val_loss: 58.3705
Epoch 30/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 64.5288 - val_loss: 55.1682
Epoch 31/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 69.1409 - val_loss: 64.1033
Epoch 32/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 68.4975 - val_loss: 60.7403
Epoch 33/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 62.2029 - val_loss: 51.9907
Epoch 34/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 62.4297 - val_loss: 52.9547
Epoch 35/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 59.6065 - val_loss: 55.2441
Epoch 36/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 59.2145 - val_loss: 53.0157
Epoch 37/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 57.1521 - val_loss: 56.8756
Epoch 38/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 57.8808 - val_loss: 51.0095
Epoch 39/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 58.4043 - val_loss: 53.5910
Epoch 40/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 56.4116 - val_loss: 52.8097
Epoch 41/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 62.1058 - val_loss: 54.9612
Epoch 42/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 57.1788 - val_loss: 49.8385
Epoch 43/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 52.0770 - val_loss: 56.7788
Epoch 44/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 53.3767 - val_loss: 45.1237
Epoch 45/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 51.7001 - val_loss: 43.9555
Epoch 46/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 52.0577 - val_loss: 42.9331
Epoch 47/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 52.7279 - val_loss: 52.9212
Epoch 48/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 62.9197 - val_loss: 44.7224
Epoch 49/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 51.3314 - val_loss: 44.3806
Epoch 50/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 52.3738 - val_loss: 46.4649
Epoch 51/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 52.3086 - val_loss: 62.3348
Epoch 52/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 52.0949 - val_loss: 62.4514
Epoch 53/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 51.9761 - val_loss: 49.4989
Epoch 54/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 54.1828 - val_loss: 83.3939
Epoch 55/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 63.4543 - val_loss: 68.4825
Epoch 56/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 58.0973 - val_loss: 55.5231
Epoch 57/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 49.9742 - val_loss: 43.1113
Epoch 58/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 49.8759 - val_loss: 44.2134
Epoch 59/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 43.3134 - val_loss: 38.9241
Epoch 60/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 42.4365 - val_loss: 38.4654
Epoch 61/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 41.5095 - val_loss: 43.5748
Epoch 62/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 41.5930 - val_loss: 39.5880
Epoch 63/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 41.1630 - val_loss: 43.1751
Epoch 64/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 42.4754 - val_loss: 49.0400
Epoch 65/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 44.5386 - val_loss: 43.8307
Epoch 66/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 39.9478 - val_loss: 38.1940
Epoch 67/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 40.9531 - val_loss: 54.3877
Epoch 68/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 42.4486 - val_loss: 37.8690
Epoch 69/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 42.7602 - val_loss: 38.8636
Epoch 70/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 44.2401 - val_loss: 41.9426
Epoch 71/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 39.8953 - val_loss: 35.9187
Epoch 72/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 40.9575 - val_loss: 37.2501
Epoch 73/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 37.5354 - val_loss: 41.8786
Epoch 74/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 45.0532 - val_loss: 43.2222
Epoch 75/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 45.7830 - val_loss: 38.1333
Epoch 76/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 42.0268 - val_loss: 36.1644
Epoch 77/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 40.7345 - val_loss: 50.9735
Epoch 78/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 49.7622 - val_loss: 83.1622
Epoch 79/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 45.5165 - val_loss: 43.9058
Epoch 80/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 44.7339 - val_loss: 35.7640
Epoch 81/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 45.2595 - val_loss: 41.3457
Epoch 82/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 43.9624 - val_loss: 39.8421
Epoch 83/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 42.0538 - val_loss: 48.2829
Epoch 84/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 40.8484 - val_loss: 38.1963
Epoch 85/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 39.6619 - val_loss: 37.1144
Epoch 86/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 38.9110 - val_loss: 37.5167
Epoch 87/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 34.5510 - val_loss: 37.1820
Epoch 88/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 35.0394 - val_loss: 38.2336
Epoch 89/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 40.9389 - val_loss: 37.1631
Epoch 90/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 40.8488 - val_loss: 38.0051
Epoch 91/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 38.2709 - val_loss: 36.7956
Epoch 92/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 35.9210 - val_loss: 46.7544
Epoch 93/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 36.0293 - val_loss: 35.7958
Epoch 94/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 35.5189 - val_loss: 42.9709
Epoch 95/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 34.1353 - val_loss: 36.4221
Epoch 96/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 36.3779 - val_loss: 52.8813
Epoch 97/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 51.6272 - val_loss: 67.6472
Epoch 98/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 47.3009 - val_loss: 38.5591
Epoch 99/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 38.5589 - val_loss: 37.2128
Epoch 100/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 37.7703 - val_loss: 38.3971
Epoch 101/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 38.5008 - val_loss: 38.2975
Epoch 102/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 34.6799 - val_loss: 38.3978
Epoch 103/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 37.7961 - val_loss: 53.6769
Epoch 104/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 40.7693 - val_loss: 36.0054
Epoch 105/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 33.6204 - val_loss: 38.8414
Epoch 106/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 32.9607 - val_loss: 36.3304
Epoch 107/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 33.1084 - val_loss: 35.7393
Epoch 108/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 34.5842 - val_loss: 37.9563
Epoch 109/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 33.4594 - val_loss: 38.2823
Epoch 110/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 33.2902 - val_loss: 41.1143
Epoch 111/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 37.5896 - val_loss: 50.7277
Epoch 112/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 35.9519 - val_loss: 45.2781
Epoch 113/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 33.5328 - val_loss: 39.0050
Epoch 114/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 32.7385 - val_loss: 38.0366
Epoch 115/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 32.9902 - val_loss: 37.9646
Epoch 116/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 32.2805 - val_loss: 35.9588
Epoch 117/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 33.9521 - val_loss: 37.8182
Epoch 118/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 33.9375 - val_loss: 39.2972
Epoch 119/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 31.7356 - val_loss: 35.8599
Epoch 120/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 35.1845 - val_loss: 38.2807

In [40]:
tahmin=model.predict(x_test)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step

In [41]:
r2_score(y_test,tahmin)

0.8514417088607308

In [42]:
mean_squared_error(y_test,tahmin) ** .5

6.187136826200252

In [43]:
# Deep learning ile makine Öğrenmemizin sonucunda r2 score u %85 mean squared error u %6 bulduk şimdi classification bölümüne geçeceğiz

In [44]:
def green_classifier(s):
    if(s.Slag+s.FlyAsh<150.0)and (s.Plasticizer<10.0):
        return "n/a"
    else:
        return "green"

In [45]:
def strength_classifier(x):
    if x< 17.0:
        return "non-structural"
    elif x < 28.0:
        return "residential"
    elif x < 70.0:
        return "commercial"
    else:
        return "high-strength"

In [46]:
df["Green"]=df.apply(green_classifier,axis=1)

In [47]:
df["ConcreteClass"] = df.Strength.apply(strength_classifier)

In [48]:
df.Plasticizer = df.Plasticizer.apply(lambda x: "yes" if x > 0 else "no")

In [49]:
df.drop("Strength", axis=1, inplace=True)

In [50]:
df.head()

,Cement,Slag,FlyAsh,Water,Plasticizer,CoarseAgg,FineAgg,Age,Green,ConcreteClass
0,540.0,0.0,0.0,162.0,yes,1040.0,676.0,28,n/a,high-strength
1,540.0,0.0,0.0,162.0,yes,1055.0,676.0,28,n/a,commercial
2,332.5,142.5,0.0,228.0,no,932.0,594.0,270,n/a,commercial
3,332.5,142.5,0.0,228.0,no,932.0,594.0,365,n/a,commercial
4,198.6,132.4,0.0,192.0,no,978.4,825.5,360,n/a,commercial

In [51]:
X= df.drop("ConcreteClass", axis=1)
Y= df["ConcreteClass"]

In [52]:
num_cols = ['Cement', 'Slag', 'FlyAsh', 'Water', 'CoarseAgg', 'FineAgg', 'Age']
cat_cols = ['Plasticizer', 'Green']

In [63]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), num_cols),
        ('cat', OneHotEncoder(drop='first'), cat_cols)
    ]
)

In [64]:
X_processed = preprocessor.fit_transform(X)

In [65]:
x_train, x_test, y_train, y_test = train_test_split(
    X_processed, Y_encoded, test_size=0.2, random_state=42, stratify=Y_encoded
)

In [72]:
model=Sequential()
model.add(Dense(80,activation="relu"))
model.add(Dense(120,activation="relu"))
model.add(Dense(64,activation="relu"))
model.add(Dense(30,activation="relu"))
model.add(Dense(8,activation="relu"))
model.add(Dense(4,activation="softmax"))
model.compile(loss="sparse_categorical_crossentropy",optimizer="adam",metrics=["accuracy"])

In [73]:
from tensorflow.keras.callbacks import EarlyStopping

In [75]:
early_stop = EarlyStopping(monitor="val_loss", patience=10)

history = model.fit(x_train, y_train,validation_data=(x_test, y_test),epochs=130,batch_size=32,callbacks=[early_stop],verbose=1)

Epoch 1/130
26/26 ━━━━━━━━━━━━━━━━━━━━ 5s 25ms/step - accuracy: 0.6129 - loss: 1.1710 - val_accuracy: 0.6165 - val_loss: 0.9127
Epoch 2/130
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6772 - loss: 0.8241 - val_accuracy: 0.7184 - val_loss: 0.7148
Epoch 3/130
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7294 - loss: 0.6645 - val_accuracy: 0.7621 - val_loss: 0.6414
Epoch 4/130
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.7427 - loss: 0.6098 - val_accuracy: 0.7670 - val_loss: 0.5810
Epoch 5/130
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7791 - loss: 0.5437 - val_accuracy: 0.7718 - val_loss: 0.5601
Epoch 6/130
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7791 - loss: 0.5142 - val_accuracy: 0.7913 - val_loss: 0.5663
Epoch 7/130
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7864 - loss: 0.5155 - val_accuracy: 0.7476 - val_loss: 0.6017
Epoch 8/130
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8265 - loss: 0.4554 - val_accuracy: 0.7816 - val_loss: 0.5618
Epoch 9/130
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.8240 - loss: 0.4394 - val_accuracy: 0.8010 - val_loss: 0.5434
Epoch 10/130
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8083 - loss: 0.4330 - val_accuracy: 0.8107 - val_loss: 0.5403
Epoch 11/130
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8252 - loss: 0.4039 - val_accuracy: 0.8350 - val_loss: 0.5042
Epoch 12/130
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8532 - loss: 0.3852 - val_accuracy: 0.8252 - val_loss: 0.5138
Epoch 13/130
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8289 - loss: 0.3829 - val_accuracy: 0.8252 - val_loss: 0.4787
Epoch 14/130
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8447 - loss: 0.3659 - val_accuracy: 0.8447 - val_loss: 0.4897
Epoch 15/130
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.8410 - loss: 0.3590 - val_accuracy: 0.7913 - val_loss: 0.5599
Epoch 16/130
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8556 - loss: 0.3380 - val_accuracy: 0.8544 - val_loss: 0.4825
Epoch 17/130
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8568 - loss: 0.3243 - val_accuracy: 0.7961 - val_loss: 0.5641
Epoch 18/130
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8665 - loss: 0.3186 - val_accuracy: 0.8689 - val_loss: 0.4636
Epoch 19/130
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8665 - loss: 0.2922 - val_accuracy: 0.8447 - val_loss: 0.5034
Epoch 20/130
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8665 - loss: 0.2976 - val_accuracy: 0.8010 - val_loss: 0.6091
Epoch 21/130
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8811 - loss: 0.2761 - val_accuracy: 0.8398 - val_loss: 0.5235
Epoch 22/130
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8774 - loss: 0.2901 - val_accuracy: 0.8398 - val_loss: 0.5360
Epoch 23/130
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8847 - loss: 0.2721 - val_accuracy: 0.8010 - val_loss: 0.6209
Epoch 24/130
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.8908 - loss: 0.2653 - val_accuracy: 0.8641 - val_loss: 0.5235
Epoch 25/130
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8968 - loss: 0.2451 - val_accuracy: 0.8592 - val_loss: 0.5118
Epoch 26/130
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8896 - loss: 0.2515 - val_accuracy: 0.8058 - val_loss: 0.5818
Epoch 27/130
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8968 - loss: 0.2558 - val_accuracy: 0.8107 - val_loss: 0.5977
Epoch 28/130
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.8714 - loss: 0.2825 - val_accuracy: 0.8252 - val_loss: 0.5933

In [76]:
tahmin = model.predict(x_test)

WARNING:tensorflow:5 out of the last 15 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x00000256B28D3CE0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step

In [77]:
tahmin_siniflari = np.argmax(tahmin, axis=1)

In [78]:
basari_orani = accuracy_score(y_test, tahmin_siniflari)

In [79]:
basari_orani

0.8252427184466019